import Link from 'next/link';
import { ArrowUpRight, Mail } from 'lucide-react';
import { alsoBuilt, featuredProjects } from '@/content/projects';
import { site } from '@/content/site';

const process = ['Map the workflow and user constraints', 'Design the simplest useful interface', 'Build with maintainable content and integrations', 'Test edge cases, polish mobile, and ship'];
const stack = ['Next.js', 'TypeScript', 'React', 'Tailwind CSS', 'Supabase', 'Twilio', 'Vercel', 'Discord APIs', 'Square', 'Testing'];

export default function Home() {
  return <main>
    <section className="relative overflow-hidden"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,rgba(124,92,255,.28),transparent_32%),radial-gradient(circle_at_80%_0%,rgba(56,213,255,.18),transparent_28%)]"/><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 md:grid-cols-[1.1fr_.9fr] md:py-28"><div><p className="kicker">{site.role}</p><h1 className="mt-5 max-w-4xl text-5xl font-black tracking-tight md:text-7xl">{site.headline}</h1><p className="mt-6 max-w-2xl text-lg text-slate-600 dark:text-slate-300">{site.description}</p><div className="mt-8 flex flex-wrap gap-3"><a className="btn-primary" href="#projects">View projects</a><a className="btn-secondary" href={`mailto:${site.email}`}>Contact Dustin</a><a className="btn-secondary" href={site.resume}>Resume PDF</a></div><p className="mt-6 text-sm text-slate-500 dark:text-slate-400">Diese is the portfolio brand of Dustin Nieves.</p></div><div className="surface rounded-[2rem] p-6 shadow-glow"><div className="mb-4 flex items-center justify-between"><span className="font-bold">Builder Console</span><span className="rounded-full bg-emerald-500/15 px-3 py-1 text-xs text-emerald-600 dark:text-emerald-300">Progressive enhancement</span></div><div className="grid gap-3">{['Intake', 'Workflow', 'Automation', 'Analytics'].map((item, i)=><div key={item} className="rounded-2xl border border-slate-200 bg-white/70 p-4 dark:border-white/10 dark:bg-black/20" style={{transform:`translateX(${i%2?18:0}px)`}}><p className="font-semibold">{item}</p><p className="text-sm text-slate-500 dark:text-slate-400">Critical content stays in HTML, not canvas-only visuals.</p></div>)}</div></div></div></section>
    <section id="projects" className="mx-auto max-w-6xl px-5 py-16"><p className="kicker">Featured Projects</p><h2 className="mt-3 text-4xl font-black">Outcome-first case studies</h2><div className="mt-8 grid gap-5">{featuredProjects.map((p, idx)=><article className="surface rounded-3xl p-6" key={p.slug}><div className="grid gap-5 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold text-accent dark:text-cyan">0{idx+1} · {p.label}</p><h3 className="mt-2 text-3xl font-black">{p.title}</h3><p className="mt-3 text-slate-600 dark:text-slate-300">{p.summary}</p><Link className="mt-5 inline-flex items-center gap-2 font-bold" href={`/projects/${p.slug}`}>Read placeholder case study <ArrowUpRight size={16}/></Link></div><ul className="space-y-3">{p.outcomes.map(o=><li className="rounded-2xl bg-slate-100 p-4 dark:bg-white/5" key={o}>{o}</li>)}</ul></div></article>)}</div></section>
    <section className="mx-auto max-w-6xl px-5 py-16"><p className="kicker">Also Built</p><div className="mt-6 grid gap-4 md:grid-cols-4">{alsoBuilt.map(p=><article className="surface rounded-3xl p-5" key={p.slug}><p className="text-xs font-bold uppercase tracking-widest text-slate-500">{p.label}</p><h3 className="mt-3 text-xl font-black">{p.title}</h3><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{p.summary}</p></article>)}</div></section>
    <section id="process" className="mx-auto max-w-6xl px-5 py-16"><p className="kicker">Build Process</p><div className="mt-6 grid gap-4 md:grid-cols-4">{process.map((step,i)=><div className="surface rounded-3xl p-5" key={step}><span className="text-3xl font-black text-accent dark:text-cyan">{i+1}</span><p className="mt-4 font-bold">{step}</p></div>)}</div></section>
    <section id="stack" className="mx-auto max-w-6xl px-5 py-16"><p className="kicker">Stack</p><div className="mt-6 flex flex-wrap gap-3">{stack.map(s=><span className="rounded-full border border-slate-300 px-4 py-2 text-sm font-semibold dark:border-white/15" key={s}>{s}</span>)}</div></section>
    <section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 md:grid-cols-2"><div><p className="kicker">About</p><h2 className="mt-3 text-4xl font-black">Dustin Nieves builds software around real workflows.</h2></div><p className="text-lg text-slate-600 dark:text-slate-300">I’m a product-minded frontend developer who likes turning messy operational problems into clear interfaces, useful automation, and maintainable systems. I use Diese as my site brand while keeping my professional identity easy for employers to verify.</p></section>
    <section id="contact" className="mx-auto max-w-6xl px-5 py-16"><div className="surface rounded-[2rem] p-8 md:p-10"><p className="kicker">Contact</p><h2 className="mt-3 text-4xl font-black">Let’s talk about frontend, product, and workflow-heavy apps.</h2><div className="mt-8 flex flex-wrap gap-3"><a className="btn-primary inline-flex items-center gap-2" href={`mailto:${site.email}`}><Mail size={18}/> Email</a><a className="btn-secondary inline-flex items-center gap-2" href={site.linkedin}>LinkedIn</a><a className="btn-secondary inline-flex items-center gap-2" href={site.github}>GitHub</a></div></div></section>
  </main>;
}
